version: '3'
services:
    app:
        build: .
        ports:
            - '80:80'
        depends_on:
            - db
    db:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: Api
